import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        "surface-dim": "#0b1326",
        error: "#ffb4ab",
        "surface-bright": "#31394d",
        "surface-container-high": "#222a3d",
        "on-surface-variant": "#c4c6cf",
        "on-secondary-fixed": "#001c3b",
        primary: "#b4c5ff",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "on-secondary-container": "#9fbae6",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-container": "#00422b",
        "on-primary-fixed": "#00174b",
        "surface-container-low": "#131b2e",
        "inverse-primary": "#0053db",
        "secondary-fixed-dim": "#adc8f5",
        "on-secondary": "#133155",
        "tertiary-fixed-dim": "#4edea3",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-tertiary-container": "#10b981",
        "on-tertiary-fixed": "#002113",
        secondary: "#adc8f5",
        "on-background": "#dae2fd",
        tertiary: "#4edea3",
        outline: "#8e9199",
        "surface-container": "#171f33",
        "on-tertiary-fixed-variant": "#005236",
        "primary-container": "#00328b",
        "on-secondary-fixed-variant": "#2d486d",
        "on-primary": "#002a78",
        "secondary-container": "#2f4a70",
        "on-surface": "#dae2fd",
        "surface-tint": "#b4c5ff",
        "on-tertiary": "#003824",
        "on-primary-container": "#7f9fff",
        "surface-container-lowest": "#060e20",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-fixed": "#d5e3ff",
        surface: "#0b1326",
        "outline-variant": "#43474e",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
