"""add territory lat lng radius_m

Revision ID: 313fb4d468e9
Revises: 2fe198858429
Create Date: 2026-03-26 01:05:52.294978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313fb4d468e9'
down_revision: Union[str, None] = '2fe198858429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('territories', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('territories', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('territories', sa.Column('radius_m', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('territories', 'radius_m')
    op.drop_column('territories', 'lng')
    op.drop_column('territories', 'lat')
    # ### end Alembic commands ###
