"""add competitors api_keys webhooks tables

Revision ID: df54fbe2be27
Revises: f2fae743f7c4
Create Date: 2026-03-26 20:49:51.111463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df54fbe2be27'
down_revision: Union[str, None] = 'f2fae743f7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
